/**
 * Seed script — 20 real Nepal trekking packages
 * Run: npx ts-node -r tsconfig-paths/register scripts/seedPackages.ts
 * Or:  npm run seed
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const MONGO_URL = process.env.MONGO_URL!;

if (!MONGO_URL) {
  console.error('MONGO_URL is not set in .env');
  process.exit(1);
}

// ── Inline lightweight schema (no circular imports) ────────────────────────

const imageSchema = new mongoose.Schema(
  { url: String, alt: String },
  { _id: false },
);

const itinerarySchema = new mongoose.Schema(
  {
    day:         Number,
    title:       String,
    description: String,
    activities:  [String],
  },
  { _id: false },
);

const PackageModel =
  mongoose.models.Package ??
  mongoose.model(
    'Package',
    new mongoose.Schema(
      {
        slug:         { type: String, unique: true },
        title:        String,
        category:     String,
        rating:       { type: Number, default: 0 },
        reviews:      { type: Number, default: 0 },
        duration:     String,
        price:        Number,
        featureImage: imageSchema,
        gallery:      [imageSchema],
        description:  String,
        highlights:   [String],
        includes:     [String],
        location:     String,
        difficulty:   String,
        altitude:     String,
        groupSize:    String,
        bestSeason:   [String],
        itinerary:    [itinerarySchema],
        status:       { type: String, default: 'active' },
      },
      { timestamps: true },
    ),
  );

// ── Free Unsplash image URLs (public CDN — no API key needed) ──────────────

const IMG = (id: string, alt: string) => ({
  url: `https://images.unsplash.com/photo-${id}?w=1200&q=80&auto=format&fit=crop`,
  alt,
});

// ── 20 Nepal Trekking Packages ─────────────────────────────────────────────

const packages = [
  // ─────────────────────────────────────────────────────────────────── 1 ──
  {
    slug: 'everest-base-camp-trek',
    title: 'Everest Base Camp Trek',
    category: 'trekking',
    rating: 4.9,
    reviews: 312,
    duration: '14 Days',
    price: 1499,
    featureImage: IMG('1464822859801-e21d4729df97', 'Everest Base Camp trail'),
    gallery: [
      IMG('1519904981063-b0cf448d6d11', 'Khumbu Icefall'),
      IMG('1506905489716-d5f7c687ab6d', 'Namche Bazaar'),
      IMG('1475924369316-14474a1aaa8e', 'Trail to Base Camp'),
      IMG('1469474968028-56623f02e42e', 'Tengboche Monastery'),
      IMG('1547489636-d2bf4f4cb01e', 'Khumbu Glacier'),
    ],
    description:
      'Trek to the foot of the world\'s highest mountain through Sherpa villages, ancient monasteries, and stunning Himalayan scenery. Stand at 5,364 m and gaze up at Everest, Lhotse, and Nuptse.',
    highlights: [
      'Stand at Everest Base Camp (5,364 m)',
      'Sunrise panorama from Kala Patthar (5,545 m)',
      'Explore vibrant Namche Bazaar',
      'Visit Tengboche Monastery',
      'Acclimatisation walk to Everest View Hotel',
    ],
    includes: [
      'TIMS & Sagarmatha National Park permits',
      'Experienced English-speaking guide',
      'Porter (1 per 2 trekkers)',
      'Teahouse accommodation (twin sharing)',
      'All meals during trek (breakfast, lunch, dinner)',
      'Airport transfers',
    ],
    location: 'Khumbu Region, Solukhumbu',
    difficulty: 'challenging',
    altitude: '5,545 m (Kala Patthar)',
    groupSize: '2–16 people',
    bestSeason: ['March', 'April', 'May', 'October', 'November'],
    itinerary: [
      { day: 1, title: 'Arrival in Kathmandu', description: 'Welcome briefing and trip preparation.', activities: ['Hotel check-in', 'Gear check', 'Welcome dinner'] },
      { day: 2, title: 'Fly to Lukla — Trek to Phakding', description: '2,860 m. Scenic Tenzing-Hillary Airport landing, walk through pine forests.', activities: ['Flight Kathmandu–Lukla', 'Trek to Phakding (2,610 m)'] },
      { day: 3, title: 'Phakding to Namche Bazaar', description: 'Cross the famous Hillary Suspension Bridge.', activities: ['Suspension bridge crossing', 'First Everest viewpoint', 'Arrive Namche (3,440 m)'] },
      { day: 4, title: 'Acclimatisation Day — Namche', description: 'Rest day with optional hike to Everest View Hotel.', activities: ['Hike to Syangboche', 'Visit Sherpa Culture Museum'] },
      { day: 5, title: 'Namche to Tengboche', description: 'Visit famous Tengboche Monastery at 3,867 m.', activities: ['Monastery visit', 'Mountain panorama views'] },
      { day: 6, title: 'Tengboche to Dingboche', description: 'Enter the upper Khumbu valley at 4,410 m.', activities: ['Cross Imja Khola', 'Arrive Dingboche'] },
      { day: 7, title: 'Acclimatisation — Dingboche', description: 'Optional hike to Nagarjun Hill for views of Makalu.', activities: ['Rest and acclimatise', 'Short hike to ridge'] },
      { day: 8, title: 'Dingboche to Lobuche', description: '4,940 m. Walk past the Thukla memorial cairns.', activities: ['Memorial chortens', 'Arrive Lobuche'] },
      { day: 9, title: 'Lobuche to Gorak Shep — EBC', description: 'Reach Everest Base Camp (5,364 m) and return to Gorak Shep.', activities: ['Trek to EBC', 'Photograph the Khumbu Icefall'] },
      { day: 10, title: 'Kala Patthar — Descend to Pheriche', description: 'Pre-dawn summit of Kala Patthar (5,545 m) for Everest sunrise.', activities: ['Sunrise at Kala Patthar', 'Descend to Pheriche'] },
      { day: 11, title: 'Pheriche to Namche Bazaar', description: 'Descend through rhododendron forests.', activities: ['Long descent', 'Namche shopping'] },
      { day: 12, title: 'Namche to Lukla', description: 'Final day of trekking, celebrate at Lukla.', activities: ['Trek to Lukla', 'Celebration dinner'] },
      { day: 13, title: 'Fly Lukla to Kathmandu', description: 'Return flight, free afternoon in Thamel.', activities: ['Morning flight', 'Afternoon leisure'] },
      { day: 14, title: 'Departure', description: 'Transfer to international airport.', activities: ['Hotel check-out', 'Airport transfer'] },
    ],
    status: 'active',
  },

  // ─────────────────────────────────────────────────────────────────── 2 ──
  {
    slug: 'annapurna-circuit-trek',
    title: 'Annapurna Circuit Trek',
    category: 'trekking',
    rating: 4.8,
    reviews: 258,
    duration: '16 Days',
    price: 1299,
    featureImage: IMG('1486911278844-86f6b7c0cbf1', 'Annapurna Circuit mountain view'),
    gallery: [
      IMG('1475924369316-14474a1aaa8e', 'Thorong La Pass'),
      IMG('1486911278844-86f6b7c0cbf1', 'Annapurna panorama'),
      IMG('1551632436-cbf8dd35adde', 'Muktinath Temple'),
      IMG('1526772662643-615ee21e0e47', 'Poon Hill sunrise'),
      IMG('1470770903914-1b1e7e4e5e2e', 'Rhododendron forest'),
    ],
    description:
      'One of the world\'s greatest treks — circumnavigate the Annapurna massif crossing the legendary Thorong La Pass (5,416 m). Experience diverse landscapes from subtropical jungle to arid Tibetan plateau.',
    highlights: [
      'Cross Thorong La Pass (5,416 m)',
      'Visit sacred Muktinath Temple',
      'Explore the medieval town of Manang',
      'Natural hot springs at Tatopani',
      'Diverse ecosystems in a single trek',
    ],
    includes: [
      'TIMS & ACAP permits',
      'Guide and porter',
      'Teahouse meals (B/L/D)',
      'Bus transfers Besisahar–Beni',
      'First-aid kit',
    ],
    location: 'Annapurna Region, Gandaki Province',
    difficulty: 'challenging',
    altitude: '5,416 m (Thorong La)',
    groupSize: '2–14 people',
    bestSeason: ['March', 'April', 'October', 'November'],
    itinerary: [
      { day: 1, title: 'Kathmandu to Besisahar', description: 'Drive to trek start.', activities: ['6-hour drive', 'Overnight Besisahar'] },
      { day: 2, title: 'Besisahar to Bulbule', description: 'First trekking day, 842 m.', activities: ['Gentle walk', 'Rice terraces'] },
      { day: 3, title: 'Bulbule to Bahundanda', description: 'Scenic valley walk.', activities: ['Waterfalls', 'Villages'] },
      { day: 4, title: 'Bahundanda to Chame', description: '2,670 m. Enter Manang district.', activities: ['Apple orchards', 'Chame town'] },
      { day: 5, title: 'Chame to Pisang', description: 'First big mountain views.', activities: ['Annapurna II views', 'Forest trails'] },
      { day: 6, title: 'Pisang to Manang', description: '3,500 m. Acclimatisation day ahead.', activities: ['Upper or lower route option', 'Arrive Manang'] },
      { day: 7, title: 'Acclimatisation — Manang', description: 'Rest and AMS lecture by local doctor.', activities: ['Gangapurna Lake hike', 'Medical briefing'] },
      { day: 8, title: 'Manang to Yak Kharka', description: '4,018 m. Landscape turns alpine.', activities: ['High pastures', 'Yak herding'] },
      { day: 9, title: 'Yak Kharka to Thorong Phedi', description: '4,450 m. Base for pass crossing.', activities: ['Short day', 'Early sleep for dawn start'] },
      { day: 10, title: 'Thorong La Pass Crossing', description: 'Cross at 5,416 m, descend to Muktinath.', activities: ['4 AM start', 'Pass summit', 'Muktinath temple'] },
      { day: 11, title: 'Muktinath to Jomsom', description: 'Enter the arid Mustang landscape.', activities: ['Kagbeni village', 'Jomsom town'] },
      { day: 12, title: 'Jomsom to Tatopani', description: 'Hot spring village at 1,190 m.', activities: ['Scenic gorge walk', 'Hot springs soak'] },
      { day: 13, title: 'Tatopani to Ghorepani', description: 'Steep ascent through rhododendron.', activities: ['2,860 m climb', 'Arrive Ghorepani'] },
      { day: 14, title: 'Poon Hill Sunrise — Nayapul', description: 'Dawn viewpoint then descent to roadhead.', activities: ['5 AM Poon Hill (3,210 m)', 'Descend to Nayapul'] },
      { day: 15, title: 'Drive to Pokhara', description: 'End of trek, lakeside relaxation.', activities: ['Pokhara leisure', 'Phewa Lake'] },
      { day: 16, title: 'Return to Kathmandu', description: 'Flight or drive back.', activities: ['Departure'] },
    ],
    status: 'active',
  },

  // ─────────────────────────────────────────────────────────────────── 3 ──
  {
    slug: 'annapurna-base-camp-trek',
    title: 'Annapurna Base Camp Trek',
    category: 'trekking',
    rating: 4.8,
    reviews: 201,
    duration: '11 Days',
    price: 899,
    featureImage: IMG('1507003211169-0a1dd7228f2d', 'Annapurna Base Camp sanctuary'),
    gallery: [
      IMG('1454496522416-2fa93add35d3', 'Annapurna massif'),
      IMG('1507003211169-0a1dd7228f2d', 'Sanctuary amphitheatre'),
      IMG('1532274402-852f246dafad', 'Machhapuchhre peak'),
      IMG('1522165978-8aa4c4b2c44a', 'Glacial basin'),
      IMG('1483728642387-6c3bdd6c29e5', 'Rhododendron trail'),
    ],
    description:
      'Trek deep into the Annapurna Sanctuary — a glacial amphitheatre ringed by 7,000+ m peaks. One of Nepal\'s most scenic and accessible high-altitude base camps.',
    highlights: [
      'Stand at ABC surrounded by 13 Himalayan giants',
      'Sunrise and sunset on Annapurna South',
      'Walk through rhododendron forests',
      'Ghandruk Gurung village cultural experience',
      'Hot springs at Jhinu Danda',
    ],
    includes: ['TIMS & ACAP permits', 'Guide and porter', 'Teahouse accommodation', 'All meals on trek', 'Pokhara–Nayapul transfer'],
    location: 'Annapurna Sanctuary, Kaski',
    difficulty: 'moderate',
    altitude: '4,130 m (ABC)',
    groupSize: '2–12 people',
    bestSeason: ['March', 'April', 'May', 'October', 'November', 'December'],
    itinerary: [
      { day: 1, title: 'Fly to Pokhara', description: 'Lakeside city, gear check.', activities: ['Pokhara check-in', 'Evening briefing'] },
      { day: 2, title: 'Drive to Nayapul — Trek to Ghandruk', description: '1,940 m Gurung village.', activities: ['Gurung museum', 'Mountain views'] },
      { day: 3, title: 'Ghandruk to Chhomrong', description: '2,170 m. Gateway to the Sanctuary.', activities: ['Stone staircase ascent', 'Annapurna South views'] },
      { day: 4, title: 'Chhomrong to Dovan', description: 'Enter bamboo and rhododendron zone.', activities: ['Himalayan Black Bear zone', 'Modi Khola valley'] },
      { day: 5, title: 'Dovan to Machhapuchhre Base Camp', description: '3,700 m below the sacred Fish Tail peak.', activities: ['Glacial moraine', 'First view of sanctuary'] },
      { day: 6, title: 'MBC to Annapurna Base Camp', description: '4,130 m — 360° panorama of the Annapurna range.', activities: ['Sunrise photography', 'Glacier views'] },
      { day: 7, title: 'Descend to Bamboo', description: 'Fast descent through the sanctuary.', activities: ['Reverse route', 'Hot spring preview'] },
      { day: 8, title: 'Bamboo to Jhinu Danda', description: 'Natural hot spring soak.', activities: ['Jhinu hot springs', 'Rest day'] },
      { day: 9, title: 'Jhinu to Nayapul', description: 'Final trekking day.', activities: ['Village trails', 'Drive to Pokhara'] },
      { day: 10, title: 'Pokhara — Leisure Day', description: 'Phewa Lake boat ride, paragliding option.', activities: ['Lake activities', 'Shopping'] },
      { day: 11, title: 'Return to Kathmandu', description: 'Flight or drive.', activities: ['Departure'] },
    ],
    status: 'active',
  },

  // ─────────────────────────────────────────────────────────────────── 4 ──
  {
    slug: 'langtang-valley-trek',
    title: 'Langtang Valley Trek',
    category: 'trekking',
    rating: 4.7,
    reviews: 143,
    duration: '9 Days',
    price: 749,
    featureImage: IMG('1483728642387-6c3bdd6c29e5', 'Langtang valley yaks'),
    gallery: [
      IMG('1551632436-cbf8dd35adde', 'Kyanjin Gompa monastery'),
      IMG('1483728642387-6c3bdd6c29e5', 'Langtang valley yaks'),
      IMG('1445789357-86d4c3fe4c3e', 'Tamang village'),
      IMG('1469474968028-56623f02e42e', 'Mountain trail'),
      IMG('1458442845773-0aed89d89c02', 'Himalayan sunrise'),
    ],
    description:
      'Closest major trek to Kathmandu. Walk through dense forests into the "Valley of Glaciers", home to the Tamang people, yak cheese factories, and the sacred Kyanjin Gompa.',
    highlights: [
      'Panoramic views from Kyanjin Ri (4,773 m)',
      'Visit ancient Kyanjin Gompa',
      'Taste fresh yak cheese at local dairy',
      'Ganesh Himal and Langtang Lirung views',
      'Tamang and Tibetan culture',
    ],
    includes: ['Langtang NP permit & TIMS', 'Guide and porter', 'Teahouse B/L/D', 'Jeep transfer Kathmandu–Syabrubesi'],
    location: 'Langtang National Park, Rasuwa',
    difficulty: 'moderate',
    altitude: '4,773 m (Kyanjin Ri)',
    groupSize: '2–12 people',
    bestSeason: ['March', 'April', 'May', 'October', 'November', 'December'],
    itinerary: [
      { day: 1, title: 'Drive Kathmandu to Syabrubesi', description: '7-hour scenic drive through mountain roads.', activities: ['Jeep/bus transfer', 'Overnight Syabrubesi (1,460 m)'] },
      { day: 2, title: 'Syabrubesi to Lama Hotel', description: 'Enter the Langtang forest.', activities: ['Bamboo forest', 'Waterfalls', '2,380 m'] },
      { day: 3, title: 'Lama Hotel to Langtang Village', description: 'Memorial to 2015 earthquake victims.', activities: ['Rebuilt village visit', 'Memorial chorten'] },
      { day: 4, title: 'Langtang to Kyanjin Gompa', description: '3,870 m. Trek end point.', activities: ['Yak cheese factory', 'Monastery visit'] },
      { day: 5, title: 'Kyanjin Ri Day Hike', description: 'Optional climb to 4,773 m for 360° views.', activities: ['Summit hike', 'Tserko Ri option (4,984 m)'] },
      { day: 6, title: 'Kyanjin to Lama Hotel', description: 'Begin descent.', activities: ['Reverse route', 'Photography'] },
      { day: 7, title: 'Lama Hotel to Syabrubesi', description: 'Final trekking day.', activities: ['Forest descent', 'Celebration dinner'] },
      { day: 8, title: 'Drive back to Kathmandu', description: 'Return journey.', activities: ['Jeep transfer', 'Thamel free time'] },
      { day: 9, title: 'Departure', description: 'Airport transfer.', activities: ['Checkout'] },
    ],
    status: 'active',
  },

  // ─────────────────────────────────────────────────────────────────── 5 ──
  {
    slug: 'poon-hill-trek',
    title: 'Poon Hill Trek',
    category: 'trekking',
    rating: 4.6,
    reviews: 389,
    duration: '5 Days',
    price: 449,
    featureImage: IMG('1526772662643-615ee21e0e47', 'Poon Hill sunrise Annapurna'),
    gallery: [
      IMG('1470770903914-1b1e7e4e5e2e', 'Ghorepani rhododendron forest'),
      IMG('1526772662643-615ee21e0e47', 'Poon Hill viewpoint'),
      IMG('1454496522416-2fa93add35d3', 'Annapurna range'),
      IMG('1507003211169-0a1dd7228f2d', 'Gurung village'),
      IMG('1532274402-852f246dafad', 'Mountain trail'),
    ],
    description:
      'The perfect short trek for first-timers. Watch the sunrise paint the Annapurna and Dhaulagiri ranges gold from Poon Hill viewpoint (3,210 m) — one of Nepal\'s most photographed vistas.',
    highlights: [
      'Iconic sunrise from Poon Hill (3,210 m)',
      'Annapurna I, II, III, IV and Dhaulagiri views',
      'Rhododendron forests in full bloom (spring)',
      'Gurung village culture at Ghandruk',
    ],
    includes: ['ACAP & TIMS permits', 'Guide', 'Teahouse B/L/D', 'Pokhara–Nayapul transfer'],
    location: 'Annapurna Foothills, Kaski / Myagdi',
    difficulty: 'easy',
    altitude: '3,210 m (Poon Hill)',
    groupSize: '1–20 people',
    bestSeason: ['February', 'March', 'April', 'October', 'November', 'December'],
    itinerary: [
      { day: 1, title: 'Pokhara — Drive to Nayapul — Trek to Tikhedhunga', description: 'Start trekking from Nayapul (1,070 m).', activities: ['Easy valley walk', 'Birethanti village'] },
      { day: 2, title: 'Tikhedhunga to Ghorepani', description: 'Climb through giant rhododendron forest to 2,860 m.', activities: ['Stone staircase', 'Sunset Annapurna view'] },
      { day: 3, title: 'Poon Hill Sunrise — Trek to Tadapani', description: 'Dawn hike to viewpoint, then to 2,630 m Tadapani.', activities: ['5 AM Poon Hill', 'Rhododendron ridge walk'] },
      { day: 4, title: 'Tadapani to Ghandruk', description: 'Traditional Gurung village at 1,940 m.', activities: ['Cultural visit', 'Mountain panorama'] },
      { day: 5, title: 'Ghandruk to Nayapul — Pokhara', description: 'Descend to road, drive to Pokhara.', activities: ['Final walk', 'Lakeside lunch'] },
    ],
    status: 'active',
  },

  // ─────────────────────────────────────────────────────────────────── 6 ──
  {
    slug: 'manaslu-circuit-trek',
    title: 'Manaslu Circuit Trek',
    category: 'trekking',
    rating: 4.8,
    reviews: 97,
    duration: '15 Days',
    price: 1599,
    featureImage: IMG('1501854140851-a503-f27b1d04ed54', 'Manaslu Circuit remote trail'),
    gallery: [
      IMG('1469474968028-56623f02e42e', 'Larkya La Pass'),
      IMG('1501854140851-a503-f27b1d04ed54', 'Manaslu Circuit trail'),
      IMG('1486911278844-86f6b7c0cbf1', 'Mountain panorama'),
      IMG('1519904981063-b0cf448d6d11', 'High altitude camp'),
      IMG('1547489636-d2bf4f4cb01e', 'Glacier views'),
    ],
    description:
      'A restricted-area circuit around the world\'s 8th highest peak (8,163 m). More remote and less crowded than Annapurna, with stunning crossings over Larkya La Pass (5,160 m).',
    highlights: [
      'Cross Larkya La Pass (5,160 m)',
      'Restricted area — pristine and uncrowded',
      'Tibetan Buddhist monasteries and culture',
      'Manaslu peak views throughout',
      'Nubri and Tsum valley indigenous cultures',
    ],
    includes: ['Restricted Area Permit (RAP)', 'Manaslu Conservation Area Permit', 'Guide (mandatory) and porter', 'Teahouse full board', 'Gorkha–Arughat–Soti Khola transport'],
    location: 'Manaslu Conservation Area, Gorkha',
    difficulty: 'challenging',
    altitude: '5,160 m (Larkya La)',
    groupSize: '2–10 people',
    bestSeason: ['March', 'April', 'May', 'October', 'November'],
    itinerary: [
      { day: 1, title: 'Drive Kathmandu to Soti Khola', description: '8-hour drive to trek start.', activities: ['Overland journey', 'Overnight Soti Khola'] },
      { day: 2, title: 'Soti Khola to Machhakhola', description: 'Subtropical forest and river.', activities: ['Suspension bridges', '870 m'] },
      { day: 3, title: 'Machhakhola to Jagat', description: 'Enter the Budhi Gandaki gorge.', activities: ['Gorge views', '1,410 m'] },
      { day: 4, title: 'Jagat to Deng', description: 'Culture shifts to Tibetan Buddhist.', activities: ['Mani walls', 'Prayer flags'] },
      { day: 5, title: 'Deng to Namrung', description: '2,630 m, first Manaslu views.', activities: ['First Manaslu sighting', 'Gompa visit'] },
      { day: 6, title: 'Namrung to Samagaon', description: '3,530 m. Rest day option.', activities: ['Pungyen Gompa day hike', 'Birendra Lake'] },
      { day: 7, title: 'Acclimatisation — Samagaon', description: 'Hike above village for altitude adaptation.', activities: ['Manaslu BC approach hike'] },
      { day: 8, title: 'Samagaon to Samdo', description: '3,860 m, near Tibetan border.', activities: ['Nubri valley views'] },
      { day: 9, title: 'Samdo to Dharamsala', description: '4,460 m high camp before pass.', activities: ['Short acclimatisation day'] },
      { day: 10, title: 'Cross Larkya La Pass', description: 'Highest point 5,160 m, descend to Bimthang.', activities: ['Pre-dawn start', 'Pass crossing', 'Bimthang (3,590 m)'] },
      { day: 11, title: 'Bimthang to Tilije', description: 'Long descent into lower valley.', activities: ['Apple orchards', '2,300 m'] },
      { day: 12, title: 'Tilije to Dharapani', description: 'Meet the Annapurna Circuit trail.', activities: ['Rejoin main trail', 'Bus option'] },
      { day: 13, title: 'Drive Dharapani to Besisahar', description: 'Jeep ride through the valley.', activities: ['Off-road drive'] },
      { day: 14, title: 'Besisahar to Kathmandu', description: 'Return by bus or jeep.', activities: ['Long drive'] },
      { day: 15, title: 'Departure Day', description: 'Rest or departure.', activities: ['Checkout'] },
    ],
    status: 'active',
  },

  // ─────────────────────────────────────────────────────────────────── 7 ──
  {
    slug: 'gokyo-lakes-trek',
    title: 'Gokyo Lakes Trek',
    category: 'trekking',
    rating: 4.7,
    reviews: 118,
    duration: '12 Days',
    price: 1199,
    featureImage: IMG('1475924369316-14474a1aaa8e', 'Gokyo turquoise lake Everest'),
    gallery: [
      IMG('1519904981063-b0cf448d6d11', 'Gokyo Ri summit view'),
      IMG('1475924369316-14474a1aaa8e', 'Gokyo turquoise lakes'),
      IMG('1464822859801-e21d4729df97', 'Ngozumpa Glacier'),
      IMG('1506905489716-d5f7c687ab6d', 'Khumbu valley'),
      IMG('1469474968028-56623f02e42e', 'High pass crossing'),
    ],
    description:
      'Visit the stunning turquoise Gokyo lakes and summit Gokyo Ri (5,357 m) for arguably the finest panoramic view in Nepal — four 8,000 m peaks visible simultaneously.',
    highlights: [
      'Summit Gokyo Ri (5,357 m) — panorama of 4 eight-thousanders',
      'Six sacred glacial Gokyo Lakes',
      'Ngozumpa Glacier — Nepal\'s largest glacier',
      'Renjo La Pass option (5,360 m)',
      'Less crowded than EBC route',
    ],
    includes: ['Sagarmatha NP & TIMS permits', 'Guide and porter', 'Lukla flights', 'Teahouse full board'],
    location: 'Gokyo Valley, Solukhumbu',
    difficulty: 'challenging',
    altitude: '5,357 m (Gokyo Ri)',
    groupSize: '2–12 people',
    bestSeason: ['March', 'April', 'May', 'October', 'November'],
    itinerary: [
      { day: 1, title: 'Kathmandu', description: 'Arrival and briefing.', activities: ['Hotel', 'Gear check'] },
      { day: 2, title: 'Fly Kathmandu–Lukla, Trek to Phakding', description: 'Same EBC start, diverge later.', activities: ['Lukla flight', 'Trek to 2,610 m'] },
      { day: 3, title: 'Phakding to Namche Bazaar', description: '3,440 m. Sherpa capital.', activities: ['Hillary Bridge', 'Namche'] },
      { day: 4, title: 'Acclimatisation Namche', description: 'Day hike and rest.', activities: ['Syangboche viewpoint', 'Sherpa museum'] },
      { day: 5, title: 'Namche to Dole', description: 'Leave EBC route, head west to Gokyo.', activities: ['Phortse village', 'Alpine meadow'] },
      { day: 6, title: 'Dole to Machhermo', description: '4,470 m. High yak grazing grounds.', activities: ['Yak herds', 'Snow peaks'] },
      { day: 7, title: 'Machhermo to Gokyo', description: '4,790 m. First two Gokyo lakes.', activities: ['Lake I & II', 'Gokyo village'] },
      { day: 8, title: 'Gokyo Ri Summit Day', description: 'Summit 5,357 m for Everest, Lhotse, Makalu, Cho Oyu views.', activities: ['Pre-dawn climb', 'All 6 lakes walk'] },
      { day: 9, title: 'Gokyo to Dole', description: 'Begin descent.', activities: ['Ngozumpa Glacier edge walk'] },
      { day: 10, title: 'Dole to Namche', description: 'Return to Namche.', activities: ['Descend valley', 'Last teahouse dinner'] },
      { day: 11, title: 'Namche to Lukla', description: 'Final trek day.', activities: ['Descend to Lukla', 'Celebration'] },
      { day: 12, title: 'Fly Lukla–Kathmandu', description: 'Return flight.', activities: ['Morning flight', 'Thamel free time'] },
    ],
    status: 'active',
  },

  // ─────────────────────────────────────────────────────────────────── 8 ──
  {
    slug: 'upper-mustang-trek',
    title: 'Upper Mustang Trek',
    category: 'trekking',
    rating: 4.9,
    reviews: 76,
    duration: '14 Days',
    price: 2499,
    featureImage: IMG('1544197289249-f9cd7a8d7e7e', 'Upper Mustang cave city desert'),
    gallery: [
      IMG('1558618047-3563c059fa3b', 'Lo Manthang walled city'),
      IMG('1544197289249-f9cd7a8d7e7e', 'Mustang desert landscape'),
      IMG('1498429089284-41f8cf3ffd39', 'Canyon trails'),
      IMG('1578662996442-48f60103fc96', 'Ancient cave monastery'),
      IMG('1523906730537-87a6c4e5c43b', 'Tibetan plateau'),
    ],
    description:
      'Trek into the forbidden kingdom of Lo — a mystical, arid landscape of eroded canyons, ancient cave cities, and the medieval walled capital Lo Manthang. A truly off-the-beaten-track adventure.',
    highlights: [
      'Explore Lo Manthang — last walled city of Nepal',
      'Ancient cave monastery of Luri Gompa',
      'Moon-like Tibetan plateau landscape',
      'Living Bon and Buddhist cultures',
      'Restricted area — limited visitors per year',
    ],
    includes: ['Upper Mustang Restricted Area Permit ($500)', 'ACAP permit', 'Mandatory licensed guide', 'Porter', 'Jeep Pokhara–Jomsom', 'Teahouse full board'],
    location: 'Upper Mustang, Mustang District',
    difficulty: 'moderate',
    altitude: '3,840 m (Lo Manthang)',
    groupSize: '2–10 people',
    bestSeason: ['May', 'June', 'July', 'August', 'September', 'October'],
    itinerary: [
      { day: 1, title: 'Fly Kathmandu–Pokhara', description: 'Transfer day.', activities: ['Pokhara overnight'] },
      { day: 2, title: 'Fly Pokhara–Jomsom, Trek to Kagbeni', description: 'Enter restricted zone at Kagbeni.', activities: ['Permit checkpoint', 'Medieval village'] },
      { day: 3, title: 'Kagbeni to Chele', description: 'Enter upper Mustang proper.', activities: ['Kali Gandaki gorge', 'Wind erosion landscape'] },
      { day: 4, title: 'Chele to Syangboche', description: 'Cross two high passes.', activities: ['Taklam La & Dajori La passes', 'Canyon views'] },
      { day: 5, title: 'Syangboche to Ghami', description: 'Large village with ancient monastery.', activities: ['Ghami Gompa', 'Mani wall (world\'s longest)'] },
      { day: 6, title: 'Ghami to Tsarang', description: 'Ancient dzong fortress.', activities: ['Tsarang Palace ruins', 'Monastery library'] },
      { day: 7, title: 'Tsarang to Lo Manthang', description: 'Arrive at the walled capital.', activities: ['City walls entry', 'Royal Palace'] },
      { day: 8, title: 'Lo Manthang Exploration', description: 'Full day in the medieval city.', activities: ['Thubchen Gompa', 'Jampa Lhakhang', 'Namgyal Gompa'] },
      { day: 9, title: 'Day Hike to Luri Gompa', description: 'Cave monastery with sky-burials platform.', activities: ['5th century cave frescoes', 'Yak cheese lunch'] },
      { day: 10, title: 'Lo Manthang to Drakmar', description: 'Begin southern return.', activities: ['Red cliffs', 'New route'] },
      { day: 11, title: 'Drakmar to Ghami', description: 'Scenic alternate route.', activities: ['Mountain views', 'Apple villages'] },
      { day: 12, title: 'Ghami to Kagbeni', description: 'Quick descent.', activities: ['Return to Kali Gandaki'] },
      { day: 13, title: 'Fly Jomsom–Pokhara', description: 'Exit restricted area.', activities: ['Short flight', 'Lakeside dinner'] },
      { day: 14, title: 'Return to Kathmandu', description: 'Flight back.', activities: ['Departure'] },
    ],
    status: 'active',
  },

  // ─────────────────────────────────────────────────────────────────── 9 ──
  {
    slug: 'three-passes-trek',
    title: 'Everest Three Passes Trek',
    category: 'trekking',
    rating: 4.8,
    reviews: 84,
    duration: '20 Days',
    price: 1899,
    featureImage: IMG('1547489636-d2bf4f4cb01e', 'Kongma La pass Khumbu glacier'),
    gallery: [
      IMG('1464822859801-e21d4729df97', 'Khumbu valley panorama'),
      IMG('1547489636-d2bf4f4cb01e', 'Kongma La Pass'),
      IMG('1519904981063-b0cf448d6d11', 'Everest Base Camp'),
      IMG('1475924369316-14474a1aaa8e', 'Three passes route'),
      IMG('1469474968028-56623f02e42e', 'Renjo La crossing'),
    ],
    description:
      'The ultimate Khumbu adventure — cross all three high passes of the Everest region: Renjo La (5,360 m), Cho La (5,420 m), and Kongma La (5,535 m), plus Everest Base Camp and Gokyo Lakes.',
    highlights: [
      'Three high passes: Renjo La, Cho La, Kongma La',
      'Everest Base Camp (5,364 m)',
      'Gokyo Lakes and Gokyo Ri summit',
      'Kala Patthar for Everest sunrise',
      'Hardest standard Khumbu trek',
    ],
    includes: ['Sagarmatha NP & TIMS', 'Guide and porter', 'Lukla flights', 'Full teahouse board'],
    location: 'Khumbu, Solukhumbu',
    difficulty: 'extreme',
    altitude: '5,545 m (Kala Patthar)',
    groupSize: '2–10 people',
    bestSeason: ['March', 'April', 'May', 'October', 'November'],
    itinerary: [
      { day: 1, title: 'Kathmandu briefing', description: 'Permits and preparation.', activities: ['Gear check', 'Briefing'] },
      { day: 2, title: 'Fly to Lukla — Namche', description: 'Two-day approach.', activities: ['Lukla flight', 'Trek to Phakding'] },
      { day: 3, title: 'Phakding to Namche', description: '3,440 m.', activities: ['Hillary Bridge', 'Namche'] },
      { day: 4, title: 'Acclimatisation Namche', description: 'Day hike.', activities: ['Everest View Hotel hike'] },
      { day: 5, title: 'Namche to Thame', description: 'Go west toward Renjo La.', activities: ['Thame village', 'Monastery'] },
      { day: 6, title: 'Thame to Lungden', description: '4,380 m. Renjo La prep camp.', activities: ['High pastures'] },
      { day: 7, title: 'Cross Renjo La — Gokyo', description: '5,360 m pass, first 8,000 m panorama.', activities: ['Pass crossing', 'Gokyo arrival'] },
      { day: 8, title: 'Gokyo Ri Summit', description: '5,357 m — four 8,000 m peaks.', activities: ['Dawn summit', 'Lakes walk'] },
      { day: 9, title: 'Gokyo to Dzongla', description: 'Traverse toward Cho La.', activities: ['Ngozumpa Glacier edge'] },
      { day: 10, title: 'Cross Cho La — Lobuche', description: '5,420 m — glaciated pass.', activities: ['Icy pass', 'Crampon section'] },
      { day: 11, title: 'Lobuche to EBC via Gorak Shep', description: 'Reach Everest Base Camp.', activities: ['EBC 5,364 m', 'Khumbu Icefall photo'] },
      { day: 12, title: 'Kala Patthar Sunrise — Chukhung', description: '5,545 m dawn, then east to Chukhung valley.', activities: ['Kala Patthar summit', 'Imja Valley approach'] },
      { day: 13, title: 'Chukhung to Kongma La prep', description: 'High camp.', activities: ['Acclimatisation hike'] },
      { day: 14, title: 'Cross Kongma La — Namche', description: 'Final pass 5,535 m, big descent.', activities: ['Third pass', 'Long descent to Namche'] },
      { day: 15, title: 'Namche to Lukla', description: 'Last two trek days.', activities: ['Descend to Phakding then Lukla'] },
      { day: 16, title: 'Fly Lukla–Kathmandu', description: 'Return flight.', activities: ['Morning flight'] },
      { day: 17, title: 'Rest Kathmandu', description: 'Rest.', activities: ['Spa', 'Shopping'] },
      { day: 18, title: 'Kathmandu sightseeing', description: 'Optional city tour.', activities: ['Boudhanath', 'Pashupatinath'] },
      { day: 19, title: 'Free day', description: 'Last shopping.', activities: ['Thamel'] },
      { day: 20, title: 'Departure', description: 'Airport transfer.', activities: ['Checkout'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 10 ──
  {
    slug: 'mardi-himal-trek',
    title: 'Mardi Himal Trek',
    category: 'trekking',
    rating: 4.6,
    reviews: 167,
    duration: '7 Days',
    price: 649,
    featureImage: IMG('1532274402-852f246dafad', 'Mardi Himal high camp Annapurna'),
    gallery: [
      IMG('1487730116645-74f0d7d21a02', 'Mardi Himal ridge view'),
      IMG('1532274402-852f246dafad', 'High camp sunrise'),
      IMG('1454496522416-2fa93add35d3', 'Machhapuchhre close-up'),
      IMG('1507003211169-0a1dd7228f2d', 'Rhododendron canopy'),
      IMG('1526772662643-615ee21e0e47', 'Annapurna south face'),
    ],
    description:
      'A hidden gem trail to the foot of Mardi Himal (5,587 m). The ridge-top forest trail offers intimate Machhapuchhre (Fish Tail) and Annapurna South views, far fewer crowds than neighbouring treks.',
    highlights: [
      'Exclusive Mardi Himal High Camp (4,500 m)',
      'Closest legal approach to Machhapuchhre',
      'Forest and rhododendron ridge walk',
      'Viewpoint sunrise with Annapurna range',
    ],
    includes: ['ACAP & TIMS', 'Guide', 'Teahouse full board', 'Pokhara–Kande transport'],
    location: 'Mardi Himal, Kaski',
    difficulty: 'moderate',
    altitude: '4,500 m (High Camp)',
    groupSize: '1–12 people',
    bestSeason: ['February', 'March', 'April', 'October', 'November', 'December'],
    itinerary: [
      { day: 1, title: 'Drive Pokhara to Kande — Trek to Forest Camp', description: 'Enter dense subtropical forest.', activities: ['Start at Kande (1,770 m)', 'Forest Camp (2,600 m)'] },
      { day: 2, title: 'Forest Camp to Low Camp', description: 'Rhododendron ridgeline.', activities: ['Ridge trail', 'Low Camp (3,150 m)'] },
      { day: 3, title: 'Low Camp to High Camp', description: 'Alpine meadows open up.', activities: ['Panoramic views', 'High Camp (4,500 m)'] },
      { day: 4, title: 'High Camp to Mardi Himal Base Camp', description: 'Dawn walk on the ridge.', activities: ['4,800 m viewpoint', 'Return to High Camp'] },
      { day: 5, title: 'High Camp to Low Camp', description: 'Begin descent.', activities: ['Same ridge reverse'] },
      { day: 6, title: 'Low Camp to Siding Village', description: 'Alternative descent route.', activities: ['Gurung village', 'Tea houses'] },
      { day: 7, title: 'Siding to Pokhara', description: 'Drive back to lakeside.', activities: ['Finish trek', 'Pokhara leisure'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 11 ──
  {
    slug: 'gosaikunda-helambu-trek',
    title: 'Gosaikunda & Helambu Trek',
    category: 'trekking',
    rating: 4.5,
    reviews: 92,
    duration: '10 Days',
    price: 799,
    featureImage: IMG('1522165978-8aa4c4b2c44a', 'Gosaikunda sacred lake'),
    gallery: [
      IMG('1483728642387-6c3bdd6c29e5', 'Helambu valley view'),
      IMG('1522165978-8aa4c4b2c44a', 'Gosaikunda Lake'),
      IMG('1551632436-cbf8dd35adde', 'Lauribina Pass'),
      IMG('1470770903914-1b1e7e4e5e2e', 'Rhododendron forest'),
      IMG('1445789357-86d4c3fe4c3e', 'Hyolmo village'),
    ],
    description:
      'Trek to the sacred alpine Gosaikunda Lake (4,380 m) — a revered Shiva pilgrimage site — then descend through the traditional Hyolmo culture of the Helambu valley.',
    highlights: [
      'Sacred Gosaikunda Lake (4,380 m)',
      'Lauribinayak Pass (4,610 m)',
      'Hyolmo Buddhist culture',
      'Closest high-altitude lake to Kathmandu',
    ],
    includes: ['Langtang NP & TIMS permits', 'Guide and porter', 'Teahouse full board', 'Kathmandu–Dhunche bus'],
    location: 'Langtang NP / Helambu, Rasuwa / Sindhupalchowk',
    difficulty: 'moderate',
    altitude: '4,610 m (Lauribinayak)',
    groupSize: '2–12 people',
    bestSeason: ['March', 'April', 'May', 'September', 'October', 'November'],
    itinerary: [
      { day: 1, title: 'Drive Kathmandu to Dhunche', description: '7 hours to Langtang trailhead.', activities: ['Bus/jeep transfer'] },
      { day: 2, title: 'Dhunche to Sing Gompa', description: '3,350 m. Cheese factory village.', activities: ['Yak cheese tasting', 'Himalayan views'] },
      { day: 3, title: 'Sing Gompa to Gosaikunda', description: 'Cross Lauribina Pass (4,610 m), descend to sacred lake.', activities: ['Pass crossing', 'Lake puja'] },
      { day: 4, title: 'Gosaikunda Exploration', description: 'Rest and explore the lake complex.', activities: ['Lower Gosaikunda', 'Saraswati and Bhairav lakes'] },
      { day: 5, title: 'Gosaikunda to Ghopte', description: 'Descend via Lauribinayak.', activities: ['Rhododendron forest'] },
      { day: 6, title: 'Ghopte to Tharepati', description: '3,490 m. Enter Helambu.', activities: ['Panoramic views', 'Juniper forest'] },
      { day: 7, title: 'Tharepati to Melamchi Gaon', description: '2,530 m. Hyolmo village.', activities: ['Buddhist monastery', 'Cultural interaction'] },
      { day: 8, title: 'Melamchi Gaon to Tarkeghyang', description: 'Gompa-rich valley.', activities: ['Multiple monastery visits'] },
      { day: 9, title: 'Tarkeghyang to Melamchi Bazaar', description: 'Descend to valley floor.', activities: ['Bus connection'] },
      { day: 10, title: 'Drive back to Kathmandu', description: 'End of trek.', activities: ['Return journey'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 12 ──
  {
    slug: 'kanchenjunga-base-camp-trek',
    title: 'Kanchenjunga Base Camp Trek',
    category: 'trekking',
    rating: 4.9,
    reviews: 41,
    duration: '22 Days',
    price: 2199,
    featureImage: IMG('1540202404-1fde49f340be', 'Kanchenjunga massif north base camp'),
    gallery: [
      IMG('1506905489716-d5f7c687ab6d', 'Yalung glacier south base camp'),
      IMG('1540202404-1fde49f340be', 'Kanchenjunga north face'),
      IMG('1578662996442-48f60103fc96', 'Remote wilderness trail'),
      IMG('1547489636-d2bf4f4cb01e', 'Tamur River gorge'),
      IMG('1458442845773-0aed89d89c02', 'Eastern Himalaya'),
    ],
    description:
      'A true wilderness expedition to both the North (5,143 m) and South (5,700 m) Base Camps of the world\'s third highest peak. Extremely remote, raw Himalayan beauty with almost no other trekkers.',
    highlights: [
      'Both North (5,143 m) and South (5,700 m) Base Camps',
      'World\'s 3rd highest peak up close',
      'Pristine wilderness — very few trekkers',
      'Tamur River gorge and waterfalls',
      'Traditional Rai and Limbu cultures',
    ],
    includes: ['Kanchenjunga Conservation Area permit', 'Restricted Area Permit', 'Mandatory guide', 'Porter', 'Flight Kathmandu–Taplejung', 'Full board teahouse'],
    location: 'Taplejung, Koshi Province',
    difficulty: 'extreme',
    altitude: '5,700 m (South Base Camp)',
    groupSize: '2–8 people',
    bestSeason: ['March', 'April', 'May', 'October', 'November'],
    itinerary: [
      { day: 1, title: 'Fly Kathmandu–Taplejung', description: 'Remote eastern Nepal.', activities: ['Arrive Taplejung', 'Overnight'] },
      { day: 2, title: 'Taplejung to Mitlung', description: 'Follow Tamur River.', activities: ['Valley forests', '900 m'] },
      { day: 3, title: 'Mitlung to Chirwa', description: 'Deeper into gorge.', activities: ['Waterfalls', 'Rai villages'] },
      { day: 4, title: 'Chirwa to Lelep', description: '1,680 m. Enter conservation area.', activities: ['Permit check', 'Village'] },
      { day: 5, title: 'Lelep to Ghunsa', description: '3,410 m. Sherpa-Tibetan village.', activities: ['Gompa visit', 'Yak pastures'] },
      { day: 6, title: 'Ghunsa to Khambachen', description: '4,050 m. Kanchenjunga appears.', activities: ['First full view', 'Glacier moraine'] },
      { day: 7, title: 'Khambachen to Lhonak', description: '4,790 m. High altitude plateau.', activities: ['Multiple glaciers', 'Acclimatisation'] },
      { day: 8, title: 'North Base Camp', description: '5,143 m. North face views.', activities: ['Pangpema viewpoint', 'Return Lhonak'] },
      { day: 9, title: 'Descent to Ghunsa', description: 'Big descent.', activities: ['Return route'] },
      { day: 10, title: 'Rest day Ghunsa', description: 'Prepare for southern route.', activities: ['Cultural visit'] },
      { day: 11, title: 'Ghunsa to Sele La Base', description: 'Cross toward south route.', activities: ['Different valley'] },
      { day: 12, title: 'Cross Sele La (4,335 m)', description: 'Connect north and south routes.', activities: ['Pass crossing', 'Ramche'] },
      { day: 13, title: 'Ramche to Tortong', description: 'South route descent.', activities: ['Yalung glacier approach'] },
      { day: 14, title: 'Tortong to Tseram', description: '3,870 m. South face views begin.', activities: ['Kanchenjunga south face'] },
      { day: 15, title: 'Tseram to Oktang (South BC)', description: '5,700 m — highest point.', activities: ['South Base Camp', 'Yalung glacier walk'] },
      { day: 16, title: 'Tseram to Yamphudin', description: 'Long descent.', activities: ['Rhododendron forest'] },
      { day: 17, title: 'Yamphudin to Khamdang', description: 'Lower valley.', activities: ['Limbu villages'] },
      { day: 18, title: 'Khamdang to Taplejung', description: 'Return to start.', activities: ['Jeep road section'] },
      { day: 19, title: 'Fly Taplejung–Kathmandu', description: 'Return flight.', activities: ['Departure'] },
      { day: 20, title: 'Rest in Kathmandu', description: 'Recovery day.', activities: ['Spa', 'Shopping'] },
      { day: 21, title: 'Kathmandu sightseeing', description: 'Optional UNESCO sites.', activities: ['Boudhanath', 'Bhaktapur'] },
      { day: 22, title: 'Departure', description: 'International flight.', activities: ['Airport transfer'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 13 ──
  {
    slug: 'tamang-heritage-trail',
    title: 'Tamang Heritage Trail',
    category: 'trekking',
    rating: 4.6,
    reviews: 108,
    duration: '8 Days',
    price: 699,
    featureImage: IMG('1445789357-86d4c3fe4c3e', 'Tamang village monastery Langtang'),
    gallery: [
      IMG('1483728642387-6c3bdd6c29e5', 'Traditional Tamang house'),
      IMG('1445789357-86d4c3fe4c3e', 'Tamang monastery'),
      IMG('1551632436-cbf8dd35adde', 'Prayer flags valley'),
      IMG('1522165978-8aa4c4b2c44a', 'Hot springs Tatopani'),
      IMG('1458442845773-0aed89d89c02', 'Ganesh Himal views'),
    ],
    description:
      'Discover the living culture of the Tamang people — an ancient Tibetan-origin community. Visit hidden monasteries, traditional homes, and enjoy authentic village life near Langtang.',
    highlights: [
      'Authentic Tamang Buddhist culture',
      'Multiple ancient gompas and mani walls',
      'Local homestay option',
      'Views of Ganesh Himal and Langtang',
      'Post-earthquake resilience — rebuilt communities',
    ],
    includes: ['Langtang NP & TIMS permits', 'Guide and porter', 'Tea house full board', 'Syabrubesi bus transfer'],
    location: 'Rasuwa District, Langtang',
    difficulty: 'easy',
    altitude: '2,300 m (Tatopani)',
    groupSize: '1–15 people',
    bestSeason: ['February', 'March', 'April', 'October', 'November', 'December'],
    itinerary: [
      { day: 1, title: 'Drive Kathmandu to Syabrubesi', description: '7-hour mountain drive.', activities: ['Arrive 1,460 m', 'Overnight'] },
      { day: 2, title: 'Syabrubesi to Gatlang', description: 'First Tamang village 2,238 m.', activities: ['Parvati Kund lake', 'Monastery visit'] },
      { day: 3, title: 'Gatlang to Tatopani', description: 'Hot spring village.', activities: ['Natural hot springs', 'Tamang cultural show'] },
      { day: 4, title: 'Tatopani to Thuman', description: 'High ridge walk.', activities: ['Ganesh Himal views', 'Traditional homes'] },
      { day: 5, title: 'Thuman to Briddim', description: 'Traditional Tamang village 2,229 m.', activities: ['Cheese factory', 'Local weaving'] },
      { day: 6, title: 'Briddim to Lama Hotel', description: 'Descend to Langtang valley.', activities: ['Dense forest', 'Meet main Langtang trail'] },
      { day: 7, title: 'Lama Hotel to Syabrubesi', description: 'Return to road head.', activities: ['River valley walk'] },
      { day: 8, title: 'Drive back to Kathmandu', description: 'End of trek.', activities: ['Bus/jeep transfer'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 14 ──
  {
    slug: 'rara-lake-trek',
    title: 'Rara Lake Trek',
    category: 'trekking',
    rating: 4.7,
    reviews: 63,
    duration: '10 Days',
    price: 1299,
    featureImage: IMG('1577717456-b55a7f0e8827', 'Rara Lake turquoise Nepal'),
    gallery: [
      IMG('1475924369316-14474a1aaa8e', 'Rara National Park forest'),
      IMG('1577717456-b55a7f0e8827', 'Rara Lake turquoise'),
      IMG('1578662996442-48f60103fc96', 'Remote western Nepal'),
      IMG('1487730116645-74f0d7d21a02', 'Murma Top viewpoint'),
      IMG('1498429089284-41f8cf3ffd39', 'Mugu valley'),
    ],
    description:
      'Trek to Nepal\'s largest and deepest lake — the jewel of the remote mid-west. Rara Lake shimmers at 2,990 m amid pristine pine and juniper forest of Rara National Park. Truly off the grid.',
    highlights: [
      'Rara Lake — Nepal\'s largest lake (10.8 km²)',
      'Rara National Park — red panda and deer habitat',
      'Remote western Nepal — barely touched by tourism',
      'Murma Top viewpoint (3,800 m)',
      'Traditional Mugu cultures',
    ],
    includes: ['Rara NP permit & TIMS', 'Guide and porter', 'Flights Kathmandu–Nepalgunj–Jumla', 'Teahouse/tent camp full board'],
    location: 'Rara National Park, Mugu',
    difficulty: 'moderate',
    altitude: '3,800 m (Murma Top)',
    groupSize: '2–10 people',
    bestSeason: ['March', 'April', 'May', 'October', 'November'],
    itinerary: [
      { day: 1, title: 'Fly Kathmandu–Nepalgunj', description: 'Transit hub.', activities: ['Overnight Nepalgunj'] },
      { day: 2, title: 'Fly Nepalgunj–Jumla', description: 'Trek start at 2,370 m.', activities: ['Jumla bazaar', 'Gear final check'] },
      { day: 3, title: 'Jumla to Chautha', description: 'Apple orchards of Jumla.', activities: ['Apple farm visits', '2,750 m'] },
      { day: 4, title: 'Chautha to Sinja', description: 'Ancient Karnali civilisation capital.', activities: ['Sinja ruins', '2,430 m'] },
      { day: 5, title: 'Sinja to Bumra', description: 'Cross first pass.', activities: ['Forest trail', '3,500 m pass'] },
      { day: 6, title: 'Bumra to Rara Lake', description: 'First view of the shimmering lake.', activities: ['Lake arrival', 'Swimming (summer)', 'Camp'] },
      { day: 7, title: 'Rara Lake Circuit', description: 'Full circumnavigation of the lake.', activities: ['4-hour circuit', 'Wildlife spotting', 'Murma Top sunset'] },
      { day: 8, title: 'Rara to Gamgadhi', description: 'Descend to Mugu district HQ.', activities: ['River crossing', 'Local market'] },
      { day: 9, title: 'Gamgadhi to Jumla', description: 'Trek back to airport.', activities: ['Steady trail', 'Overnight Jumla'] },
      { day: 10, title: 'Fly Jumla–Nepalgunj–Kathmandu', description: 'Return journey.', activities: ['Two connecting flights'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 15 ──
  {
    slug: 'dhaulagiri-circuit-trek',
    title: 'Dhaulagiri Circuit Trek',
    category: 'trekking',
    rating: 4.8,
    reviews: 38,
    duration: '18 Days',
    price: 2099,
    featureImage: IMG('1549880481-af3e3a39fa03', 'Dhaulagiri massif glacier'),
    gallery: [
      IMG('1486911278844-86f6b7c0cbf1', 'French Pass Dhaulagiri'),
      IMG('1549880481-af3e3a39fa03', 'Dhaulagiri glacier'),
      IMG('1542314831-068cd1dbfeeb', 'Hidden Valley plateau'),
      IMG('1469474968028-56623f02e42e', 'Myagdi gorge'),
      IMG('1475924369316-14474a1aaa8e', 'Dhampus Pass crossing'),
    ],
    description:
      'A raw, challenging circuit around the world\'s 7th highest peak (8,167 m). Cross the French Pass (5,360 m) and Dhampus Pass (5,182 m) on one of Nepal\'s least-trekked but most dramatic routes.',
    highlights: [
      'Cross French Pass (5,360 m) and Dhampus Pass (5,182 m)',
      'Dhaulagiri Base Camp (4,750 m)',
      'Crevassed Hidden Valley plateau at 5,000 m+',
      'Myagdi gorge — deepest in the world',
      'One of Nepal\'s hardest non-technical treks',
    ],
    includes: ['ACAP & TIMS', 'Guide and porter', 'Camping full board', 'Tent & sleeping equipment', 'Pokhara–Beni transport'],
    location: 'Myagdi / Mustang Districts',
    difficulty: 'extreme',
    altitude: '5,360 m (French Pass)',
    groupSize: '2–8 people',
    bestSeason: ['April', 'May', 'October'],
    itinerary: [
      { day: 1, title: 'Drive Pokhara to Beni', description: 'Trek starts from Beni (830 m).', activities: ['Drive transfer', 'Overnight Beni'] },
      { day: 2, title: 'Beni to Babiyachaur', description: 'Enter Myagdi valley.', activities: ['River walk', '1,060 m'] },
      { day: 3, title: 'Babiyachaur to Muri', description: 'Valley deepens.', activities: ['Village visits', '1,850 m'] },
      { day: 4, title: 'Muri to Dobang', description: 'Enter Dhaulagiri zone.', activities: ['First glacial views', '2,970 m'] },
      { day: 5, title: 'Dobang to Italian Base Camp', description: '3,660 m. Dramatic glacier camp.', activities: ['Moraine walk', 'Camp setup'] },
      { day: 6, title: 'Italian BC to Dhaulagiri BC', description: '4,750 m. Full face view.', activities: ['Glacier navigation', 'Base camp'] },
      { day: 7, title: 'Rest at Dhaulagiri BC', description: 'Acclimatisation.', activities: ['Short hikes', 'Views'] },
      { day: 8, title: 'BC to Fedzung (Hidden Valley approach)', description: '5,000 m+ plateau.', activities: ['Snow travel', 'Camp'] },
      { day: 9, title: 'Cross French Pass (5,360 m)', description: 'Technical snowy pass.', activities: ['Pass crossing', 'Crampon section', 'Yak Kharka'] },
      { day: 10, title: 'Cross Dhampus Pass (5,182 m)', description: 'Second pass crossing.', activities: ['Aerial valley views', 'Descend to Dampus'] },
      { day: 11, title: 'Dampus to Marpha', description: 'Arrive in Mustang apple town.', activities: ['Apple brandy tasting', '2,670 m'] },
      { day: 12, title: 'Marpha to Ghasa', description: 'Along Kali Gandaki gorge.', activities: ['World\'s deepest gorge', 'Waterfalls'] },
      { day: 13, title: 'Ghasa to Tatopani', description: 'Hot springs village.', activities: ['Hot spring soak'] },
      { day: 14, title: 'Tatopani to Ghorepani', description: 'Climb through rhododendron.', activities: ['Steep ascent', '2,860 m'] },
      { day: 15, title: 'Poon Hill — Descend to Nayapul', description: 'End of trek.', activities: ['Dawn Poon Hill', 'Nayapul finish'] },
      { day: 16, title: 'Drive to Pokhara', description: 'Return to city.', activities: ['Pokhara leisure'] },
      { day: 17, title: 'Pokhara rest', description: 'Lakeside recovery.', activities: ['Phewa lake', 'Massage'] },
      { day: 18, title: 'Return to Kathmandu', description: 'Flight or bus.', activities: ['Departure'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 16 ──
  {
    slug: 'nar-phu-valley-trek',
    title: 'Nar Phu Valley Trek',
    category: 'trekking',
    rating: 4.8,
    reviews: 52,
    duration: '14 Days',
    price: 1799,
    featureImage: IMG('1523906730537-87a6c4e5c43b', 'Nar Phu hidden valley Annapurna'),
    gallery: [
      IMG('1486911278844-86f6b7c0cbf1', 'Kang La pass restricted area'),
      IMG('1523906730537-87a6c4e5c43b', 'Nar Phu hidden valley'),
      IMG('1498429089284-41f8cf3ffd39', 'Tibetan-style village'),
      IMG('1544197289249-f9cd7a8d7e7e', 'Phu walled village'),
      IMG('1542314831-068cd1dbfeeb', 'Canyon trail Nar'),
    ],
    description:
      'A restricted, hidden Himalayan valley frozen in time — the Nar Phu valley feels like Tibet before the border closed. Ancient salt-trade route villages, dramatic canyon landscapes, and the Kang La Pass (5,320 m).',
    highlights: [
      'Restricted area — pristine and crowd-free',
      'Phu and Nar villages — authentic Tibetan culture',
      'Kang La Pass (5,320 m) crossing',
      'Baroque mud-brick fortress villages',
      'Pisang Peak (6,091 m) mountaineering option',
    ],
    includes: ['Restricted Area Permit ($90/week)', 'ACAP permit', 'Mandatory guide', 'Porter', 'Teahouse full board'],
    location: 'Nar Phu Valley, Manang District',
    difficulty: 'challenging',
    altitude: '5,320 m (Kang La)',
    groupSize: '2–10 people',
    bestSeason: ['March', 'April', 'October', 'November'],
    itinerary: [
      { day: 1, title: 'Kathmandu to Besisahar', description: 'Start of Annapurna circuit approach.', activities: ['Drive transfer'] },
      { day: 2, title: 'Besisahar to Koto', description: 'Diverge from circuit into restricted area.', activities: ['Permit check at Koto gate'] },
      { day: 3, title: 'Koto to Meta', description: '3,560 m. First Nar Phu sights.', activities: ['Red canyon walls', 'Tibetan village'] },
      { day: 4, title: 'Meta to Phu', description: '4,080 m. Ancient walled village.', activities: ['Tashi Lhakhang Gompa', 'Village exploration'] },
      { day: 5, title: 'Phu rest day', description: 'Acclimatise and explore.', activities: ['Gompa visit', 'Day hike to glacier'] },
      { day: 6, title: 'Phu to Nar Phedi', description: 'Cross inner valley.', activities: ['Canyon trail', 'Camp 4,200 m'] },
      { day: 7, title: 'Nar Phedi to Nar', description: '4,110 m. Second walled village.', activities: ['Mani walls', 'Festival if timed right'] },
      { day: 8, title: 'Nar acclimatisation', description: 'Rest and explore Nar.', activities: ['Gompa', 'Kang La preparation'] },
      { day: 9, title: 'Cross Kang La (5,320 m)', description: 'Technical high pass back to Annapurna circuit.', activities: ['Pass crossing', 'Descend to Ngawal'] },
      { day: 10, title: 'Ngawal to Manang', description: 'Rejoin circuit at 3,500 m.', activities: ['Annapurna views', 'Rest in Manang'] },
      { day: 11, title: 'Manang to Yak Kharka', description: 'Continue circuit south.', activities: ['4,018 m', 'High pastures'] },
      { day: 12, title: 'Cross Thorong La (5,416 m)', description: 'Legendary Annapurna circuit pass.', activities: ['Pre-dawn crossing', 'Muktinath arrival'] },
      { day: 13, title: 'Muktinath to Jomsom', description: 'Fly Jomsom–Pokhara.', activities: ['10 min flight', 'Pokhara overnight'] },
      { day: 14, title: 'Return Kathmandu', description: 'End of expedition.', activities: ['Flight or drive'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 17 ──
  {
    slug: 'tsum-valley-trek',
    title: 'Tsum Valley Trek',
    category: 'trekking',
    rating: 4.8,
    reviews: 47,
    duration: '16 Days',
    price: 1699,
    featureImage: IMG('1498429089284-41f8cf3ffd39', 'Tsum valley Buddhist village'),
    gallery: [
      IMG('1501854140851-a503-f27b1d04ed54', 'Ganesh Himal Tsum'),
      IMG('1498429089284-41f8cf3ffd39', 'Mu Gompa monastery'),
      IMG('1551632436-cbf8dd35adde', 'Ancient chortens Tsum'),
      IMG('1445789357-86d4c3fe4c3e', 'Milarepa Cave pilgrimage'),
      IMG('1523906730537-87a6c4e5c43b', 'Budhi Gandaki gorge'),
    ],
    description:
      'The "Hidden Valley of Happiness" — Tsum Valley was opened to trekkers only in 2008. A deeply sacred Buddhist valley under the shadow of Ganesh Himal, where ancient pilgrimage routes, chortens, and gompas remain unchanged for centuries.',
    highlights: [
      'Restricted hidden valley opened 2008',
      'Mu Gompa — largest monastery in the region',
      'Milarepa Cave pilgrimage site',
      'Rachen Gompa nunnery',
      'Ganesh Himal panoramas',
    ],
    includes: ['Manaslu Conservation Area permit', 'Tsum Valley restricted permit', 'Guide (mandatory)', 'Porter', 'Teahouse full board'],
    location: 'Tsum Valley, Gorkha District',
    difficulty: 'moderate',
    altitude: '3,700 m (Chhule)',
    groupSize: '2–10 people',
    bestSeason: ['March', 'April', 'May', 'October', 'November'],
    itinerary: [
      { day: 1, title: 'Drive Kathmandu to Soti Khola', description: '8-hour drive.', activities: ['Overnight Soti Khola'] },
      { day: 2, title: 'Soti Khola to Machhakhola', description: 'Start of trek.', activities: ['Subtropical forest', '870 m'] },
      { day: 3, title: 'Machhakhola to Doban', description: 'Budhi Gandaki gorge.', activities: ['Gorge views'] },
      { day: 4, title: 'Doban to Jagat', description: 'Enter restricted area.', activities: ['Permit check', '1,410 m'] },
      { day: 5, title: 'Jagat to Lokpa', description: 'Diverge from Manaslu route into Tsum.', activities: ['River crossing', 'Tsum Valley entry'] },
      { day: 6, title: 'Lokpa to Chumling', description: '2,386 m. First Tsum village.', activities: ['Mani walls', 'Village life'] },
      { day: 7, title: 'Chumling to Chho Kumbu', description: '3,031 m.', activities: ['Rachen Nunnery', 'Pilgrimage kora'] },
      { day: 8, title: 'Chho Kumbu to Nile', description: '3,361 m.', activities: ['Panoramic views', 'More gompas'] },
      { day: 9, title: 'Day hike to Mu Gompa', description: 'Largest monastery, 3,700 m.', activities: ['Mu Gompa visit', 'Milarepa Cave'] },
      { day: 10, title: 'Nile to Chhule', description: 'Upper valley exploration.', activities: ['Highest Tsum point', 'Ganesh Himal views'] },
      { day: 11, title: 'Begin return to Lokpa', description: 'Retrace south.', activities: ['Reverse route', 'Photography'] },
      { day: 12, title: 'Lokpa to Jagat', description: 'Exit Tsum, rejoin Manaslu route.', activities: ['Budhi Gandaki south'] },
      { day: 13, title: 'Jagat to Machhakhola', description: 'Lower valley.', activities: ['Waterfalls', 'Warm temperatures'] },
      { day: 14, title: 'Machhakhola to Soti Khola', description: 'Final trek day.', activities: ['Easy walk out'] },
      { day: 15, title: 'Drive Soti Khola to Kathmandu', description: '8-hour return.', activities: ['Overland journey'] },
      { day: 16, title: 'Departure', description: 'Rest or fly.', activities: ['Airport transfer'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 18 ──
  {
    slug: 'rolwaling-valley-trek',
    title: 'Rolwaling Valley & Tashi Lapcha Trek',
    category: 'trekking',
    rating: 4.7,
    reviews: 29,
    duration: '17 Days',
    price: 1899,
    featureImage: IMG('1542314831-068cd1dbfeeb', 'Rolwaling valley Gaurishankar'),
    gallery: [IMG('1519904981063-b0cf448d6d11', 'Tashi Lapcha Pass glaciers')],
    description:
      'One of Nepal\'s most remote valleys, dominated by the sacred twin peaks of Gaurishankar (7,134 m). Cross the technical Tashi Lapcha Pass (5,755 m) on crampons from Khumbu to Rolwaling or vice versa.',
    highlights: [
      'Tashi Lapcha Pass (5,755 m) — ropes and crampons required',
      'Rolwaling "Hidden Valley" — pristine wilderness',
      'Sacred Gaurishankar (7,134 m) views',
      'Tsho Rolpa glacial lake (4,580 m)',
      'No teahouses above Beding — full camping',
    ],
    includes: ['Permits and fees', 'Experienced high-altitude guide', 'Porter', 'Camping full board', 'Camping equipment', 'Rope and crampons for pass'],
    location: 'Rolwaling Himal, Dolakha',
    difficulty: 'extreme',
    altitude: '5,755 m (Tashi Lapcha)',
    groupSize: '2–8 people',
    bestSeason: ['April', 'May', 'October'],
    itinerary: [
      { day: 1, title: 'Drive Kathmandu to Charikot', description: '5-hour drive.', activities: ['Overnight Charikot'] },
      { day: 2, title: 'Charikot to Simigaon', description: 'Enter Rolwaling valley.', activities: ['Forest trail', '2,020 m'] },
      { day: 3, title: 'Simigaon to Dongang', description: 'Valley deepens.', activities: ['Alpine scenery'] },
      { day: 4, title: 'Dongang to Beding', description: '3,700 m. Last permanent settlement.', activities: ['Monastery', 'Last teahouse'] },
      { day: 5, title: 'Beding rest day', description: 'Acclimatise.', activities: ['Monastery visit', 'Short hike'] },
      { day: 6, title: 'Beding to Na', description: '4,180 m. Seasonal summer settlement.', activities: ['Full Gaurishankar view', 'Camp Na'] },
      { day: 7, title: 'Na — Tsho Rolpa day hike', description: '4,580 m glacial lake.', activities: ['Glacial lake visit', 'Return to Na'] },
      { day: 8, title: 'Na to Tashi Lapcha Base', description: '4,900 m high camp.', activities: ['Glacier approach', 'Crampon briefing'] },
      { day: 9, title: 'Cross Tashi Lapcha Pass (5,755 m)', description: 'Technical glaciated pass into Khumbu.', activities: ['Rope and crampon crossing', 'Descent to Thame'] },
      { day: 10, title: 'Thame rest day', description: 'Recover from pass crossing.', activities: ['Thame Gompa', 'Rest'] },
      { day: 11, title: 'Thame to Namche Bazaar', description: 'Enter Everest region.', activities: ['Namche facilities'] },
      { day: 12, title: 'Namche to Phakding', description: 'Descend Khumbu valley.', activities: ['Valley forests'] },
      { day: 13, title: 'Phakding to Lukla', description: 'Final trekking day.', activities: ['Celebration', 'Lukla'] },
      { day: 14, title: 'Fly Lukla–Kathmandu', description: 'Return flight.', activities: ['Morning flight'] },
      { day: 15, title: 'Rest in Kathmandu', description: 'Recovery.', activities: ['Thamel', 'Shopping'] },
      { day: 16, title: 'Kathmandu sightseeing', description: 'Optional tour.', activities: ['Boudhanath', 'Pashupatinath'] },
      { day: 17, title: 'Departure', description: 'International flight.', activities: ['Checkout'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 19 ──
  {
    slug: 'upper-dolpo-trek',
    title: 'Upper Dolpo Trek',
    category: 'trekking',
    rating: 4.9,
    reviews: 24,
    duration: '24 Days',
    price: 3299,
    featureImage: IMG('1578662996442-48f60103fc96', 'Shey Phoksundo Lake Dolpo blue'),
    gallery: [IMG('1544197289249-f9cd7a8d7e7e', 'Crystal Mountain Dolpo landscape')],
    description:
      'The most remote and expensive trek in Nepal — the journey to Upper Dolpo, setting of Peter Matthiessen\'s "The Snow Leopard". Ancient Bon-Buddhist culture, the incomparable Shey Phoksundo Lake, and the Crystal Mountain pilgrimage circuit.',
    highlights: [
      'Shey Phoksundo Lake (3,611 m) — Nepal\'s deepest lake',
      'Shey Gompa — Crystal Mountain pilgrimage',
      'Living Bon-Buddhist culture unchanged for millennia',
      'Kangla Pass (5,360 m) and Numala Pass (5,190 m)',
      'The "Snow Leopard" landscape — wildlife possible',
    ],
    includes: ['Upper Dolpo RAP ($500/10 days)', 'Shey Phoksundo NP permit', 'Mandatory guide', 'Porter', 'Flights Kathmandu–Nepalgunj–Juphal', 'Full camping board'],
    location: 'Dolpo, Karnali Province',
    difficulty: 'extreme',
    altitude: '5,360 m (Kangla Pass)',
    groupSize: '2–8 people',
    bestSeason: ['May', 'June', 'September', 'October'],
    itinerary: [
      { day: 1, title: 'Fly Kathmandu–Nepalgunj', description: 'Western Nepal hub.', activities: ['Overnight Nepalgunj'] },
      { day: 2, title: 'Fly Nepalgunj–Juphal', description: 'Small airstrip in Dolpo.', activities: ['Trek briefing', 'Dunai overnight'] },
      { day: 3, title: 'Dunai to Chhepka', description: 'Enter park.', activities: ['River trail', '2,840 m'] },
      { day: 4, title: 'Chhepka to Amchi Hospital', description: 'Traditional medicine clinic.', activities: ['River gorge', '3,020 m'] },
      { day: 5, title: 'To Shey Phoksundo Lake', description: '3,611 m. Turquoise wonder.', activities: ['Waterfall approach', 'Lake arrival'] },
      { day: 6, title: 'Shey Phoksundo rest day', description: 'Explore lake and gompa.', activities: ['Ringmo village', 'Tshowa Gompa'] },
      { day: 7, title: 'Cross Phoksundo La (5,050 m)', description: 'Enter upper Dolpo.', activities: ['Pass crossing', 'Upper valley'] },
      { day: 8, title: 'Towards Shey Gompa', description: '4,360 m. Approach Crystal Mountain.', activities: ['Kora route begins'] },
      { day: 9, title: 'Shey Gompa arrival', description: 'Ancient Tibetan Buddhist monastery.', activities: ['Crystal Mountain kora', 'Snow leopard habitat'] },
      { day: 10, title: 'Shey Gompa rest day', description: 'Pilgrimage circuit.', activities: ['Shey Phoksundo kora', 'Bon rituals'] },
      { day: 11, title: 'Shey to Namgung', description: 'Deeper into plateau.', activities: ['High plateau walk'] },
      { day: 12, title: 'Namgung to Saldang', description: '3,770 m. Large Dolpo village.', activities: ['Saldang Gompa', 'Traditional salt trade'] },
      { day: 13, title: 'Saldang to Yanjer', description: 'Yak herding grounds.', activities: ['High grazing pastures'] },
      { day: 14, title: 'Cross Kangla Pass (5,360 m)', description: 'Highest point of trek.', activities: ['Technical pass', 'Panoramic views'] },
      { day: 15, title: 'Descend to Tokyu', description: 'Another remote Dolpo village.', activities: ['Village visit', 'Gompa'] },
      { day: 16, title: 'Tokyu to Tinje', description: '3,980 m.', activities: ['Diverse landscape'] },
      { day: 17, title: 'Tinje to Chharka', description: 'Cross into Mustang zone.', activities: ['Wind-swept plateau'] },
      { day: 18, title: 'Chharka to Dho Tarap', description: '4,080 m. Double village.', activities: ['Ancient gompas', 'High desert'] },
      { day: 19, title: 'Cross Numala Pass (5,190 m)', description: 'Second high pass.', activities: ['Glaciated section'] },
      { day: 20, title: 'Descend to Dunai', description: 'Re-enter Lower Dolpo.', activities: ['Long descent'] },
      { day: 21, title: 'Dunai rest', description: 'Recovery before flight.', activities: ['Hot shower', 'Local market'] },
      { day: 22, title: 'Fly Juphal–Nepalgunj', description: 'Exit Dolpo.', activities: ['Morning flight'] },
      { day: 23, title: 'Fly Nepalgunj–Kathmandu', description: 'Return to capital.', activities: ['Arrival'] },
      { day: 24, title: 'Departure', description: 'International flight.', activities: ['Checkout'] },
    ],
    status: 'active',
  },

  // ────────────────────────────────────────────────────────────────── 20 ──
  {
    slug: 'pikey-peak-trek',
    title: 'Pikey Peak Trek',
    category: 'trekking',
    rating: 4.5,
    reviews: 134,
    duration: '6 Days',
    price: 549,
    featureImage: IMG('1458442845773-0aed89d89c02', 'Pikey Peak Everest view sunrise'),
    gallery: [IMG('1464822859801-e21d4729df97', 'Solu Khumbu lower hills')],
    description:
      'A brilliant short trek offering one of Nepal\'s best Everest viewpoints from Pikey Peak (4,065 m) — praised by Sir Edmund Hillary himself. Walk through rhododendron forests and authentic Sherpa villages, far cheaper and less crowded than the EBC route.',
    highlights: [
      'Pikey Peak summit (4,065 m) — Everest, Kanchenjunga, Makalu views',
      'Praised by Sir Edmund Hillary as best Everest viewpoint',
      'Authentic Sherpa culture without the EBC crowds',
      'Rhododendron and oak forest trails',
      'Budget-friendly Khumbu experience',
    ],
    includes: ['TIMS permit', 'Guide and porter', 'Teahouse full board', 'Salleri–Pikey jeep transfer'],
    location: 'Solu Khumbu, Solukhumbu',
    difficulty: 'easy',
    altitude: '4,065 m (Pikey Peak)',
    groupSize: '1–20 people',
    bestSeason: ['February', 'March', 'April', 'October', 'November', 'December'],
    itinerary: [
      { day: 1, title: 'Drive Kathmandu to Dhap', description: '6-hour drive to starting point.', activities: ['Mountain drive', 'Overnight Dhap'] },
      { day: 2, title: 'Dhap to Pikey Peak Base', description: 'Gentle ascent through forest.', activities: ['Rhododendron trail', 'Camp or teahouse base'] },
      { day: 3, title: 'Summit Pikey Peak (4,065 m)', description: 'Pre-dawn summit, full Himalayan panorama.', activities: ['Dawn summit hike', 'Everest kanchenjunga views', 'Descend to Junbesi'] },
      { day: 4, title: 'Junbesi to Ringmu', description: 'Historic Sherpa valley.', activities: ['Thubten Choling Gompa', 'Apple orchards'] },
      { day: 5, title: 'Ringmu to Salleri', description: 'Return to road.', activities: ['Village walk', 'Salleri bazaar'] },
      { day: 6, title: 'Drive Salleri to Kathmandu', description: 'Return journey.', activities: ['7-hour drive'] },
    ],
    status: 'active',
  },
];

// ── Seed function ──────────────────────────────────────────────────────────

async function seed() {
  console.log('Connecting to MongoDB...');
  await mongoose.connect(MONGO_URL);
  console.log('Connected.');

  let inserted = 0;
  let updated  = 0;

  for (const pkg of packages) {
    const result = await PackageModel.updateOne(
      { slug: pkg.slug },
      { $set: pkg },
      { upsert: true },
    );
    if (result.upsertedCount) {
      console.log(`  ✓ inserted: ${pkg.title}`);
      inserted++;
    } else {
      console.log(`  ↻ updated:  ${pkg.title}`);
      updated++;
    }
  }

  console.log(`\nDone — ${inserted} inserted, ${updated} updated.`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
